### ISSUE TITLE
inspect.getargspec() is deprecated in Python 3.0, causes errors with keyword-only arguments in 3.4.3

### ISSUE THREAD

**Issue by dewiniaid** [iurisilvio/bottle-sqlalchemy#22]
Using bottle_sqlalchemy with a route that has keyword-only arguments causes failures when attempting to execute that route.  This is particularly problematic when routing using functools.partial.

```python
def test_normal(db, value=None):
    return "Hello, world!"
bottle.route('/test_normal', 'GET', test_normal)   # Works
bottle.route('/test_partial', 'GET', functools.partial(test_normal, value=True))  # Raises below exception
@bottle.route('/test_kwonly')  # Raises below exception
def test_kwonly(db, *args, kwonly=None):
    return "Hello, world!"
```

```
Traceback (most recent call last):
  File "...venv\lib\site-packages\bottle.py", line 862, in _handle
    return route.call(**args)
  File "...venv\lib\site-packages\bottle.py", line 189, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "...venv\lib\site-packages\bottle.py", line 492, in call
    return self._make_callback()
  File "...venv\lib\site-packages\bottle.py", line 528, in _make_callback
    callback = plugin.apply(callback, context)
  File "...venv\lib\site-packages\bottle_sqlalchemy.py", line 133, in apply
    argspec = inspect.getargspec(_callback)
  File "...\lib\inspect.py", line 936, in getargspec
    raise ValueError("Function has keyword-only arguments or annotations"
ValueError: Function has keyword-only arguments or annotations, use getfullargspec() API which can support them
```

As a workaround, the function in question can use **kwargs instead of having a named argument, though this is less than ideal.

**Comment by iurisilvio** [comment]
Fixed and released 0.4.3. Thanks for the report!

It raised several other issues, because sqlalchemy does not support python 3.6 yet and failed my tests.
